version: '3.8'

services:
  backend:
    image: nvcr.io/nvidia/rapidsai/notebooks:24.12-cuda12.5-py3.12
    pull_policy: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
        EXTRA_PIP_PACKAGES: "aiobotocore==2.21.1 aioitertools==0.12.0 anndata==0.11.3 array-api-compat==1.11.1 asciitree==0.3.3 botocore==1.37.1 dask-image==2024.5.3 deprecated==1.2.18 docrep==0.3.2 fasteners==0.19 h5py==3.13.0 inflect==7.5.0 jmespath==1.0.1 legacy-api-wrap==1.4.1 matplotlib-scalebar==0.9.0 more-itertools==10.6.0 multiscale-spatial-image==2.0.2 natsort==8.4.0 numcodecs==0.15.1 ome-zarr==0.10.3 omnipath==1.0.9 pims==0.7 pip-licenses==5.0.0 pipdeptree==2.25.1 pooch==1.8.2 prettytable==3.15.1 pynndescent==0.5.13 rapids-singlecell==0.12.1 s3fs==2024.10.0 scanpy==1.11.0 scikit-misc==0.5.1 session-info2==0.1.2 slicerator==1.1.0 spatial-image==1.2.1 spatialdata==0.3.0 squidpy==1.6.4 typeguard==4.4.2 umap-learn==0.5.7 validators==0.34.0 wget==3.2 wrapt==1.17.2 xarray-dataclasses==1.9.1 xarray-schema==0.0.3 xarray-spatial==0.4.0 zarr==2.18.4"
    ports:
      - "0.0.0.0:8888:8888"      # JupyterLab
      - "0.0.0.0:8787:8787"      # Dask dashboard
      - "0.0.0.0:8786:8786"      # Dask scheduler
    volumes:
      - /home/ubuntu/single-cell-analysis-blueprint:/notebooks/
      - /ephemeral:/notebooks/data
    user: root
    working_dir: /notebooks
    entrypoint: ["/home/rapids/entrypoint.sh"]
    command: python -m jupyter lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/notebooks
    restart: unless-stopped
